### PR TITLE
Update consortium document

### PR DESCRIPTION
**Pull request by SylvainCorlay**

### CODE REVIEW

**Comment by fangohr** [comment]
Sylvain, the requirements have changed a little here. The content of this files needs to be uploaded through the portal, rather than submitted as part of the proposal. (It is of still useful to have the information here, but you will need to carry out (or delegate) this additional step.)

**Comment by SylvainCorlay** [comment]
No problem. SHould we still get this in the document?

**Comment by fangohr** [comment]
No. The files you have edited are not included in the pdf we compile and submit.

Related content is in `consortium.tex`. Could you review and edit that as well, please (in particular with respect to QS's role).

**Comment by SylvainCorlay** [comment]
Let's get this in then!

**Pull request merged**
